install.packages("librarian")
librarian::shelf(ggplot2,here,openxlsx,dplyr)
POP<-readRDS("POP.rds")
A<-read.xlsx("A.xlsx")
B<-read.xlsx("B.xlsx")
P<-read.xlsx("P.xlsx")
SthE<-read.xlsx("SouthEast.xlsx.")
tdata<-read.csv("transcribed data.csv")
View(A)
View(B)
View(P)
View(SthE)
View(tdata)
colnames(SthE)[2]<-"PH"
colnames(SthE)[3]<-"MH"
colnames(tdata)[5]<-"PH"
colnames(tdata)[6]<-"MH"
SthE$PH<-case_match(SthE$PH,"NO"~"N","YES"~"Y")
P$PH<-case_match(P$PH,"No"~"N","Yes"~"Y")
SthE$Smoker<-case_match(SthE$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
A$Smoker<-case_match(A$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
B$Smoker<-case_match(B$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
P$Smoker<-case_match(P$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
tdata$Smoker<-case_match(tdata$Smoker,"Yes"~"Y","No"~"N")
tdata$PH<-case_match(tdata$PH,"Yes"~"Y","No"~"N")
tdata$MH<-case_match(tdata$MH,"Yes"~"Y","No"~"N")
tdata$Belief<-case_match(tdata$Belief,"Yes"~"Y","No"~"N")
tdata$Gender<-case_match(tdata$Gender,"Male"~"M","Female"~"F")
SthE$Gender<-case_match(SthE$Gender,"M"~"M","F"~"F")
A$Gender<-case_match(A$Gender,"M"~"M","F"~"F")
B$Gender<-case_match(B$Gender,"M"~"M","F"~"F")
P$Gender<-case_match(P$Gender,"M"~"M","F"~"F")
AB<-rbind(A,B)
View(AB)
ABP<-rbind(AB,P)
SthE<-SthE[,-9]
ABPSthE<-rbind(ABP,SthE)
View(ABPSthE)
ABPSthE<-ABPSthE[,-2]
ABPSthE<-ABPSthE[,-6]
tdata<-tdata[,-1]
totaldata<-rbind(ABPSthE,tdata)
View(totaldata)