---
title: "Gitgoing Report"
output: html_document
date: "2025-12-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r code}
#clean data


#install required packages 
install.packages("librarian") 
librarian::shelf(ggplot2,here,openxlsx,dplyr)

#install required data
POP<-readRDS("POP.rds")
A<-read.xlsx("A.xlsx")
B<-read.xlsx("B.xlsx")
P<-read.xlsx("P.xlsx")
SthE<-read.xlsx("SouthEast.xlsx.")
tdata<-read.csv("transcribed data.csv")


#view dataframes
View(A)
View(B)
View(P)
View(SthE)
View(tdata)

#change column names to be consistent
colnames(SthE)[2]<-"PH"
colnames(SthE)[3]<-"MH"
colnames(tdata)[5]<-"PH"
colnames(tdata)[6]<-"MH"

#creating consistency between codes
SthE$PH<-case_match(SthE$PH,"NO"~"N","YES"~"Y")
P$PH<-case_match(P$PH,"No"~"N","Yes"~"Y")
SthE$Smoker<-case_match(SthE$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
A$Smoker<-case_match(A$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
B$Smoker<-case_match(B$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
P$Smoker<-case_match(P$Smoker,"Current"~"Y","Y"~"Y","N"~"N")
tdata$Smoker<-case_match(tdata$Smoker,"Yes"~"Y","No"~"N")
tdata$PH<-case_match(tdata$PH,"Yes"~"Y","No"~"N")
tdata$MH<-case_match(tdata$MH,"Yes"~"Y","No"~"N")
tdata$Belief<-case_match(tdata$Belief,"Yes"~"Y","No"~"N")
tdata$Gender<-case_match(tdata$Gender,"Male"~"M","Female"~"F")
SthE$Gender<-case_match(SthE$Gender,"M"~"M","F"~"F")
A$Gender<-case_match(A$Gender,"M"~"M","F"~"F")
B$Gender<-case_match(B$Gender,"M"~"M","F"~"F")
P$Gender<-case_match(P$Gender,"M"~"M","F"~"F")

#combining datasets into a masterframe
AB<-rbind(A,B)
View(AB)
ABP<-rbind(AB,P)
SthE<-SthE[,-9]
ABPSthE<-rbind(ABP,SthE)
View(ABPSthE)
ABPSthE<-ABPSthE[,-2]
ABPSthE<-ABPSthE[,-6]
tdata<-tdata[,-1]
totaldata<-rbind(ABPSthE,tdata)

#view dataframe created
View(totaldata)
```


```{r code}
##prepare data for binomial regression

#create dummy variables, with d after original column names to correspond to dummy in order to not change original data

tdata$MHd <-ifelse(tdata$MH == "Y", 1, 0) #make a dummy variable for mental health, with 1 equivalent to yes
tdata$PHd <- ifelse(tdata$PH == "Y", 1, 0) #make a dummy variable for physical health, with 1 equivalent to yes
tdata$Beliefd <- ifelse(tdata$Belief == "Y", 1, 0) #make a dummy variable for belief, with 1 equivalent to yes

tdata$MHd

#carry out binomial regression

m1 <- glm(Beliefd ~ PHd, family = binomial, data = tdata) #regress impact of physical health 

m2 <- glm(Beliefd ~ MHd, family = binomial, data = tdata) #regress impact of mental health

m3 <- glm(Beliefd ~ PHd + MHd, family = binomial, data = tdata) #regress impact of physical AND mental health



(summary(m1)) # table for impact of physical health on belief 
(summary(m2)) #table for impact of mental health on belief
(summary(m3)) # table for impact of physical and mental health on belief

#interpretation - belief yes, they believe their condition will get worse, 

```


This analysis found no significant evidence that individuals with on-going health issues  change believe their condition will get worse while waiting for treatment - there were no p-values under the boundary of 0.05


```{r code}




```